# Generated by Django 5.1.4 on 2025-01-08 11:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopbotfy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAFormuUserer',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='Desconhecido', max_length=300)),
                ('username', models.CharField(default='Desconhecido', max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(default='Desconhecido', max_length=300)),
                ('pais', models.CharField(default='Brasil', max_length=300)),
                ('cor', models.CharField(default='Desconhecido', max_length=200)),
                ('nicho', models.CharField(default='Genérica', max_length=200)),
                ('tema_base', models.CharField(default='Dropmeta', max_length=200)),
                ('link_store', models.URLField(default='https://example.com/default-link')),
                ('url_loja', models.CharField(default='example.com/default-link', max_length=200)),
                ('token_senha', models.CharField(default='Desconhecido', max_length=200)),
                ('chave_de_api', models.CharField(default='Desconhecido', max_length=200)),
                ('chave_secreta', models.CharField(default='Desconhecido', max_length=200)),
                ('telefone', models.CharField(default='Desconhecido', max_length=300)),
                ('email_suporte', models.EmailField(default='suporte@example.com', max_length=254)),
                ('empresa', models.CharField(default='Desconhecido', max_length=300)),
                ('business_hours', models.CharField(default='Desconhecido', max_length=300)),
                ('produtos', models.BooleanField(default=False)),
                ('resposta_produtos', models.TextField(blank=True, null=True)),
                ('tema', models.BooleanField(default=False)),
                ('resposta_tema', models.TextField(blank=True, null=True)),
                ('banners', models.BooleanField(default=False)),
                ('resposta_banners', models.TextField(blank=True, null=True)),
                ('colecoes', models.BooleanField(default=False)),
                ('resposta_colecoes', models.TextField(blank=True, null=True)),
                ('paginas', models.BooleanField(default=False)),
                ('resposta_paginas', models.TextField(blank=True, null=True)),
                ('politicas', models.BooleanField(default=False)),
                ('resposta_politicas', models.TextField(blank=True, null=True)),
                ('prod_col', models.BooleanField(default=False)),
                ('resposta_prod_col', models.TextField(blank=True, null=True)),
                ('estilizacao', models.BooleanField(default=False)),
                ('resposta_estilizacao', models.TextField(blank=True, null=True)),
                ('lojaproduzida', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('reservado', 'Reservado'), ('respondido', 'Respondido'), ('iniciado', 'Iniciado'), ('pendencia', 'Pendencia'), ('produzindo', 'Produzindo'), ('finalizado', 'Finalizado'), ('erro', 'Erro')], default='Reservado', max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopbotfy.agencia')),
            ],
        ),
        migrations.CreateModel(
            name='FilaDeEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_formulario', models.JSONField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('processado', models.BooleanField(default=False)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopbotfy.agencia')),
            ],
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='Desconhecido', max_length=300)),
                ('verificacoes', models.IntegerField(default=0)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopbotfy.agencia')),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reservado', 'Reservado'), ('respondido', 'Respondido'), ('iniciado', 'Iniciado'), ('pendencia', 'Pendencia'), ('produzindo', 'Produzindo'), ('finalizado', 'Finalizado'), ('erro', 'Erro')], max_length=20)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='shop_api.aaformuuserer')),
            ],
        ),
    ]
